CREATE TABLE IF NOT EXISTS STARSHIPS
(
    STARSHIP_ID BIGINT NOT NULL,
    STARSHIP_NAME VARCHAR(500) NOT NULL,
    MOVIE_NAME VARCHAR(500) NOT NULL,
    NUMBER_OF_PASSENGERS INTEGER,
    CONSTRAINT STARSHIPS_PK_01 PRIMARY KEY (STARSHIP_ID)
);

CREATE SEQUENCE IF NOT EXISTS STARSHIPS_SEQ;